"""empty message

Revision ID: 3836f4589265
Revises: c8d539c1f205
Create Date: 2022-06-09 08:03:41.509447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3836f4589265'
down_revision = 'c8d539c1f205'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('carp')
    op.drop_table('cook')
    op.add_column('user', sa.Column('cook', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('carp', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('paint', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_admin', table_name='user')
    op.create_index(op.f('ix_user_carp'), 'user', ['carp'], unique=False)
    op.create_index(op.f('ix_user_cook'), 'user', ['cook'], unique=False)
    op.create_index(op.f('ix_user_paint'), 'user', ['paint'], unique=False)
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    op.drop_index(op.f('ix_user_paint'), table_name='user')
    op.drop_index(op.f('ix_user_cook'), table_name='user')
    op.drop_index(op.f('ix_user_carp'), table_name='user')
    op.create_index('ix_user_admin', 'user', ['admin'], unique=False)
    op.drop_column('user', 'paint')
    op.drop_column('user', 'carp')
    op.drop_column('user', 'cook')
    op.create_table('cook',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carp',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
