"""empty message

Revision ID: aa5d2dcd8246
Revises: f34754e1d019
Create Date: 2022-06-15 01:21:22.769263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa5d2dcd8246'
down_revision = 'f34754e1d019'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    op.drop_index('ix_user_fullname', table_name='user')
    op.create_index(op.f('ix_user_fullname'), 'user', ['fullname'], unique=False)
    op.create_index(op.f('ix_user_admin'), 'user', ['admin'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_admin'), table_name='user')
    op.drop_index(op.f('ix_user_fullname'), table_name='user')
    op.create_index('ix_user_fullname', 'user', ['fullname'], unique=False)
    op.drop_column('user', 'admin')
    # ### end Alembic commands ###
