"""empty message

Revision ID: f34754e1d019
Revises: 3836f4589265
Create Date: 2022-06-09 16:40:14.456570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f34754e1d019'
down_revision = '3836f4589265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_reg', sa.String(length=32), nullable=True))
    op.add_column('user', sa.Column('gpa', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('docs', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('phone', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_docs'), 'user', ['docs'], unique=False)
    op.create_index(op.f('ix_user_gpa'), 'user', ['gpa'], unique=False)
    op.create_index(op.f('ix_user_id_reg'), 'user', ['id_reg'], unique=False)
    op.create_index(op.f('ix_user_phone'), 'user', ['phone'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_phone'), table_name='user')
    op.drop_index(op.f('ix_user_id_reg'), table_name='user')
    op.drop_index(op.f('ix_user_gpa'), table_name='user')
    op.drop_index(op.f('ix_user_docs'), table_name='user')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'docs')
    op.drop_column('user', 'gpa')
    op.drop_column('user', 'id_reg')
    # ### end Alembic commands ###
